owner: Tahoe-LAFS
repo: infrastructure-upptime

sites:
  - name: Web
    url: https://www.tahoe-lafs.org/
  - name: Tickets
    url: https://tahoe-lafs.org/trac/tahoe-lafs/query 
  - name: Wiki
    url: https://tahoe-lafs.org/trac/tahoe-lafs/wiki
  - name: GitHub
    url: https://github.com/tahoe-lafs
  - name: GitLab
    url: https://gitlab.com/tahoe-lafs
  - name: CodeBerg
    url: https://codeberg.org/tahoe-lafs
  - name: CircleCI
    url: https://app.circleci.com/pipelines/github/tahoe-lafs/tahoe-lafs
  - name: Coveralls
    url: https://coveralls.io/github/tahoe-lafs
  - name: PyPi
    url: https://pypi.org/project/tahoe-lafs/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /infrastructure-upptime
  logoUrl: https://raw.githubusercontent.com/tahoe-lafs/infrastructure-upptime/master/assets/logo_199x300.png
  name: Tahoe-LAFS
  introTitle: |
    Status page monitoring the availability of the services powering the Tahoe-LAFS infrastructure.
  introMessage: |
    Based on [**Upptime**](https://github.com/upptime/upptime), this static page shows:
    - any active incidents and scheduled maintenances based on [opened issues](https://github.com/tahoe-lafs/infrastructure-upptime/issues?q=is%3Aissue state%3Aopen)
    - a live status of all the [services](https://github.com/tahoe-lafs/infrastructure-upptime/blob/master/.upptimerc.yml) with [metrics](https://github.com/tahoe-lafs/infrastructure-upptime/tree/master/history) updated by [CI](https://github.com/tahoe-lafs/infrastructure-upptime/actions).
    - any past incidents based on [closed issues](https://github.com/tahoe-lafs/infrastructure-upptime/issues?q=is%3Aissue%20state%3Aclosed)
    Further:
    - receive notifications about new incidents and maintenances by *watching* [this repository](https://github.com/tahoe-lafs/infrastructure-upptime) (e.g. `Watch` > `Custom` > `Issues`).
    - contribute by creating an issue or submiting pull-request in [this repository](https://github.com/tahoe-lafs/infrastructure-upptime).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Do not delete issues, just close them, so we can investigate intermittent problems
skipDeleteIssues: true

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
